import * as THREE from 'three';
import {glowTexture,stars,earthWorld,coreWorld,portalWorld,moonWorld,finaleWorld} from './objects.js';
const canvas=document.getElementById('world'),fallback=document.getElementById('fallback'),loader=document.getElementById('loader'),loaderPct=document.getElementById('loaderPct'),meterFill=document.getElementById('meterFill'),mobileFill=document.getElementById('mobileFill'),meterScene=document.getElementById('meterScene'),sceneCode=document.getElementById('sceneCode'),depthValue=document.getElementById('depthValue'),hint=document.getElementById('hint'),panels=[...document.querySelectorAll('.story-panel')];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,isMobile=()=>innerWidth<780;let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:!isMobile(),alpha:false,powerPreference:'high-performance'})}catch(e){fallback.hidden=false;throw e}
function size(){renderer.setPixelRatio(Math.min(devicePixelRatio||1,isMobile()?1.35:1.65));renderer.setSize(innerWidth,innerHeight,false)}size();renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020405);scene.fog=new THREE.FogExp2(0x020405,isMobile()?.019:.013);const camera=new THREE.PerspectiveCamera(isMobile()?62:54,innerWidth/innerHeight,.08,220);scene.add(new THREE.HemisphereLight(0x9fc5db,0x090b0c,1.15));const light=new THREE.DirectionalLight(0xeaf4ff,4.25);light.position.set(8,7,10);scene.add(light);const rim=new THREE.DirectionalLight(0x8ec8ff,2);rim.position.set(-8,1,-6);scene.add(rim);
const manager=new THREE.LoadingManager();manager.onProgress=(u,l,t)=>loaderPct.textContent=String(Math.round(l/Math.max(1,t)*100)).padStart(2,'0');manager.onLoad=()=>setTimeout(()=>loader.classList.add('done'),250);const tex=glowTexture();scene.add(stars(isMobile()));
const earth=earthWorld(isMobile(),tex,manager);scene.add(earth.group);earth.group.position.set(0,isMobile()?-1.85:-.8,0);const core=coreWorld(tex);scene.add(core.group);core.group.position.z=-18;const portal=portalWorld(tex);scene.add(portal);portal.position.z=-34;const moon=moonWorld(isMobile(),tex);scene.add(moon.group);moon.group.position.z=-49;const finale=finaleWorld(tex,manager,isMobile());scene.add(finale.group);finale.group.position.z=-88;
function makeKeys(){if(isMobile())return[{p:0,pos:[0,1.35,16.2],look:[0,-2.05,0]},{p:.12,pos:[1.25,.35,11.8],look:[0,-2.0,0]},{p:.205,pos:[2.8,-.05,8.1],look:[1.7,-1.65,2.6]},{p:.255,pos:[2.1,.1,6.6],look:[2.4,-1.55,1.7]},{p:.305,pos:[-.8,.55,-8.2],look:[0,-.35,-18]},{p:.42,pos:[1.3,.2,-22.5],look:[0,-.3,-28]},{p:.52,pos:[0,0,-31.5],look:[0,-.25,-38]},{p:.665,pos:[3.2,.75,-41.2],look:[-1.2,-1.35,-46.7]},{p:.80,pos:[1.6,4.6,-55.5],look:[1,-1.35,-64]},{p:.91,pos:[0,7.4,-69],look:[0,-.75,-78]},{p:1,pos:[0,.9,-78.4],look:[0,-.9,-88]}];return[{p:0,pos:[0,1.2,14.6],look:[0,-.8,0]},{p:.13,pos:[1.8,.25,9.5],look:[0,-1,0]},{p:.21,pos:[3.2,.1,7.2],look:[2.35,-.95,1.9]},{p:.255,pos:[2.2,.1,6.4],look:[2.5,-1,1.5]},{p:.30,pos:[-.5,.4,-8.5],look:[0,0,-18]},{p:.40,pos:[1.4,.2,-22.5],look:[0,0,-28]},{p:.52,pos:[0,0,-31.5],look:[0,0,-38]},{p:.66,pos:[4.2,1.25,-40.8],look:[-1.6,-1.1,-46.7]},{p:.80,pos:[1.8,4.8,-55.5],look:[1,-1.1,-64]},{p:.91,pos:[0,7.5,-69],look:[0,-.5,-78]},{p:1,pos:[0,.8,-78.5],look:[0,-.4,-88]}]}
let keys=makeKeys();const ranges=[.11,.245,.39,.54,.715,.875,1.001],labels=['01 / EARTH','02 / NETWORK','03 / CORE','04 / TRANSIT','05 / MOON','06 / BUILD','07 / RETURN'];
function interp(pp){let a=keys[0],b=keys.at(-1);for(let i=0;i<keys.length-1;i++)if(pp>=keys[i].p&&pp<=keys[i+1].p){a=keys[i];b=keys[i+1];break}let q=(pp-a.p)/(b.p-a.p);q=q*q*(3-2*q);return{pos:a.pos.map((v,i)=>THREE.MathUtils.lerp(v,b.pos[i],q)),look:a.look.map((v,i)=>THREE.MathUtils.lerp(v,b.look[i],q))}}
function sceneIndex(pp){for(let i=0;i<ranges.length;i++)if(pp<ranges[i])return i;return 6}function local(pp,a,b){return THREE.MathUtils.clamp((pp-a)/(b-a),0,1)}let target=0,p=0,tx=0,ty=0,px=0,py=0,last=-1;
function scrollProgress(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);target=THREE.MathUtils.clamp((scrollY||0)/max,0,1)}
function updateWorld(t){const networkP=local(p,.08,.25),exitP=THREE.MathUtils.smoothstep(p,.235,.30);earth.group.position.y=THREE.MathUtils.lerp(isMobile()?-1.85:-.8,isMobile()?-2.15:-1.25,networkP);earth.group.position.x=-exitP*(isMobile()?8.5:10);earth.group.rotation.z=-exitP*.16;earth.group.scale.setScalar(1-exitP*.12);earth.earth.rotation.y=t*.00005+p*.9;earth.clouds.rotation.y=-t*.000025+p*.6;earth.network.rotation.y=p*1.1+t*.00003;earth.network.rotation.z=Math.sin(t*.00018)*.035;
const cp=local(p,.25,.44);core.group.rotation.y=t*.00018+cp*.5;core.inner.rotation.x=t*.0004;core.inner.rotation.y=-t*.0003;core.components.forEach((m,i)=>{const e=Math.sin(Math.PI*THREE.MathUtils.clamp((cp-.12)*1.35,0,1));m.position.copy(m.userData.base).multiplyScalar(.3+e*.9);m.rotation.x=e*(i%2?.4:-.35);m.rotation.y=e*(i%2?-.5:.45)});portal.rotation.z=t*.00012;
const mp=local(p,.55,.86);moon.rover.position.x=-4.7+mp*7.8;moon.rover.position.z=2.2-Math.sin(mp*Math.PI)*.8;moon.rover.rotation.y=-.42+mp*.55;moon.rover.children.forEach(o=>{if(o.userData.wheel)o.rotation.x-=.025});const build=local(p,.72,.90);moon.modules.forEach((m,i)=>{const q=THREE.MathUtils.smoothstep(build,i*.14,Math.min(1,i*.14+.34));m.scale.setScalar(Math.max(.001,q));m.position.y=-.8+q*.8;m.rotation.y=(1-q)*.7*(i%2?1:-1)});moon.tower.scale.y=Math.max(.001,THREE.MathUtils.smoothstep(build,.55,.92));
finale.earth.rotation.y=t*.00006+p;finale.ring.rotation.z=t*.0001;const fp=local(p,.89,1);finale.sunrise.position.y=-5.4+fp*1.45;finale.sunrise.scale.setScalar(.78+fp*.3);finale.sunrise.rotation.z=Math.sin(t*.00015)*.02}
function updateUI(){const idx=sceneIndex(p);if(idx!==last){panels.forEach((el,i)=>el.classList.toggle('active',i===idx));meterScene.textContent=String(idx+1).padStart(2,'0');sceneCode.textContent=labels[idx];last=idx}const pct=(p*100).toFixed(2)+'%';meterFill.style.height=pct;mobileFill.style.width=pct;const z=interp(p).pos[2];depthValue.textContent=(z>=0?'+':'')+Math.round(z).toString().padStart(3,'0')+' KM';hint.classList.toggle('hide',p>.035)}
addEventListener('scroll',scrollProgress,{passive:true});addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2},{passive:true});addEventListener('touchmove',e=>{if(e.touches[0]){tx=(e.touches[0].clientX/innerWidth-.5)*2;ty=(e.touches[0].clientY/innerHeight-.5)*2}},{passive:true});addEventListener('resize',()=>{size();keys=makeKeys();camera.aspect=innerWidth/innerHeight;camera.fov=isMobile()?62:54;camera.updateProjectionMatrix();scrollProgress()},{passive:true});
const look=new THREE.Vector3();function frame(t){p+=(target-p)*(reduce?1:.075);px+=(tx-px)*.045;py+=(ty-py)*.045;const k=interp(p);camera.position.set(k.pos[0]+px*(isMobile()?.28:.5),k.pos[1]-py*(isMobile()?.22:.38),k.pos[2]);look.set(k.look[0]+px*.15,k.look[1]-py*.12,k.look[2]);camera.lookAt(look);updateWorld(t);updateUI();renderer.render(scene,camera);requestAnimationFrame(frame)}scrollProgress();requestAnimationFrame(frame);setTimeout(()=>loader.classList.add('done'),5000);
