import * as THREE from 'three';
import {glowTexture,stars,earthWorld,coreWorld,portalWorld,moonWorld,finaleWorld} from './objects.js';
THREE.Cache.enabled=true;
const mobile=()=>innerWidth<780,canvas=document.getElementById('world'),loader=document.getElementById('loader'),fallback=document.getElementById('fallback'),loaderPct=document.getElementById('loaderPct'),meterFill=document.getElementById('meterFill'),mobileFill=document.getElementById('mobileFill'),meterScene=document.getElementById('meterScene'),sceneCode=document.getElementById('sceneCode'),depthValue=document.getElementById('depthValue'),hint=document.getElementById('hint'),panels=[...document.querySelectorAll('.story-panel')];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;let renderer,quality=1,paused=false;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile(),powerPreference:'high-performance'})}catch(e){fallback.hidden=false;throw e}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020405);scene.fog=new THREE.FogExp2(0x020405,mobile()?.011:.0075);const camera=new THREE.PerspectiveCamera(mobile()?60:53,innerWidth/innerHeight,.06,260);
function resize(){const cap=mobile()?1.18:1.5;renderer.setPixelRatio(Math.min(devicePixelRatio||1,cap)*quality);renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=mobile()?60:53;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize,{passive:true});
scene.add(new THREE.HemisphereLight(0xa7d3ec,0x050708,.9));const key=new THREE.DirectionalLight(0xf8fbff,4.3);key.position.set(-7,8,12);scene.add(key);const rim=new THREE.DirectionalLight(0x78cfff,2);rim.position.set(9,-1,-10);scene.add(rim);
const manager=new THREE.LoadingManager();manager.onProgress=(u,l,t)=>loaderPct.textContent=String(Math.round(l/Math.max(1,t)*100)).padStart(2,'0');manager.onLoad=()=>setTimeout(()=>loader.classList.add('done'),220);const tex=glowTexture();scene.add(stars(mobile()));
const earth=earthWorld(mobile(),tex,manager);earth.group.position.set(0,mobile()?-1.7:-.7,0);scene.add(earth.group);const core=coreWorld(tex);core.group.position.set(.3,-.1,-22);core.group.scale.setScalar(mobile()?.82:.94);scene.add(core.group);const portal=portalWorld(tex);portal.position.set(-.4,.1,-39);scene.add(portal);const moon=moonWorld(mobile(),tex);moon.group.position.z=-58;scene.add(moon.group);const finale=finaleWorld(tex,manager,mobile());finale.group.position.z=-102;scene.add(finale.group);
const route=new THREE.Group();scene.add(route);const routePts=[new THREE.Vector3(1.8,-.6,8),new THREE.Vector3(3,-.5,2),new THREE.Vector3(2,.2,-8),new THREE.Vector3(.4,.2,-19),new THREE.Vector3(-1,.2,-29),new THREE.Vector3(-.4,.1,-39),new THREE.Vector3(1.5,-.5,-48),new THREE.Vector3(-1.5,-1.1,-58),new THREE.Vector3(2,-1.6,-68),new THREE.Vector3(3,-1.2,-78),new THREE.Vector3(.5,1,-91),new THREE.Vector3(0,2,-100)];const routeCurve=new THREE.CatmullRomCurve3(routePts,false,'catmullrom',.22);const ribbon=new THREE.Mesh(new THREE.TubeGeometry(routeCurve,220,.018,6,false),new THREE.MeshBasicMaterial({color:0x9adfff,transparent:true,opacity:.15,depthWrite:false,blending:THREE.AdditiveBlending}));route.add(ribbon);for(let i=0;i<34;i++){const q=routeCurve.getPoint(i/33),s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,color:i%5===0?0xcaff4f:0x9bdfff,transparent:true,opacity:i%5===0?.75:.3,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.copy(q);s.scale.setScalar(i%5===0?.36:.16);route.add(s)}
const gates=[];[-10,-31,-48,-69,-88].forEach((z,i)=>{const g=new THREE.Group(),r1=new THREE.Mesh(new THREE.TorusGeometry(2.6+i*.08,.025,8,140),new THREE.MeshBasicMaterial({color:i%2?0x8fdfff:0xcaff4f,transparent:true,opacity:.16,depthWrite:false,blending:THREE.AdditiveBlending}));r1.rotation.x=Math.PI/2+(i-2)*.06;g.add(r1);const r2=r1.clone();r2.scale.setScalar(.72);r2.rotation.z=.6+i*.2;g.add(r2);g.position.set(i%2?1.8:-1.3,(i%3-1)*.45,z);scene.add(g);gates.push(g)});
const nearField=new THREE.Group();scene.add(nearField);for(let i=0;i<(mobile()?70:120);i++){const geo=new THREE.CylinderGeometry(.006,.006,.3+Math.random()*.8,4),mat=new THREE.MeshBasicMaterial({color:i%5?0x567384:0xcaff4f,transparent:true,opacity:.12+Math.random()*.16}),m=new THREE.Mesh(geo,mat);m.position.set((Math.random()-.5)*18,(Math.random()-.5)*12,-Math.random()*110+8);m.rotation.z=Math.random()*Math.PI;nearField.add(m)}
function cameraPoints(){return mobile()?[new THREE.Vector3(0,1.5,16),new THREE.Vector3(1.5,.9,10.5),new THREE.Vector3(3,.6,5),new THREE.Vector3(2,.4,-4),new THREE.Vector3(.8,.5,-13),new THREE.Vector3(1.8,.4,-19),new THREE.Vector3(-.2,.3,-27),new THREE.Vector3(-.8,.2,-36),new THREE.Vector3(.7,.4,-45),new THREE.Vector3(3,1.8,-52),new THREE.Vector3(1.5,1.3,-60),new THREE.Vector3(5,2.6,-68),new THREE.Vector3(3.8,2.2,-78),new THREE.Vector3(.5,5.5,-90),new THREE.Vector3(0,6.5,-94)]:[new THREE.Vector3(0,1.25,14.8),new THREE.Vector3(2,.7,9),new THREE.Vector3(3.5,.45,4),new THREE.Vector3(2.8,.3,-5),new THREE.Vector3(.8,.35,-13),new THREE.Vector3(2,.3,-19),new THREE.Vector3(-.2,.2,-27),new THREE.Vector3(-.7,.2,-36),new THREE.Vector3(1,.5,-45),new THREE.Vector3(4,1.8,-52),new THREE.Vector3(2,1.2,-60),new THREE.Vector3(6,2.8,-68),new THREE.Vector3(4.5,2,-78),new THREE.Vector3(.6,5.8,-90),new THREE.Vector3(0,6.8,-94)]}
function lookPoints(){return mobile()?[new THREE.Vector3(0,-1.7,0),new THREE.Vector3(0,-1.7,0),new THREE.Vector3(1,-1.3,0),new THREE.Vector3(.3,-.2,-18),new THREE.Vector3(.2,-.15,-22),new THREE.Vector3(0,-.15,-22),new THREE.Vector3(-.2,0,-39),new THREE.Vector3(-.3,0,-39),new THREE.Vector3(-1,-1.5,-58),new THREE.Vector3(-1.5,-1.7,-58),new THREE.Vector3(1,-1.8,-63),new THREE.Vector3(2,-1.7,-66),new THREE.Vector3(2,-1.3,-70),new THREE.Vector3(0,-.5,-102),new THREE.Vector3(0,-.5,-102)]:[new THREE.Vector3(0,-.9,0),new THREE.Vector3(0,-.9,0),new THREE.Vector3(1.3,-.8,0),new THREE.Vector3(.4,0,-18),new THREE.Vector3(.2,0,-22),new THREE.Vector3(0,0,-22),new THREE.Vector3(-.2,0,-39),new THREE.Vector3(-.3,0,-39),new THREE.Vector3(-1.2,-1.35,-58),new THREE.Vector3(-1.5,-1.55,-58),new THREE.Vector3(1,-1.7,-63),new THREE.Vector3(2,-1.5,-66),new THREE.Vector3(2,-1.2,-70),new THREE.Vector3(0,-.35,-102),new THREE.Vector3(0,-.35,-102)]}
let camCurve=new THREE.CatmullRomCurve3(cameraPoints(),false,'catmullrom',.25),lookCurve=new THREE.CatmullRomCurve3(lookPoints(),false,'catmullrom',.25);const ranges=[.12,.25,.41,.56,.73,.91,1.001],labels=['01 / EARTH','02 / NETWORK','03 / CORE','04 / TRANSIT','05 / MOON','06 / BUILD','07 / RETURN'];
let target=0,p=0,tx=0,ty=0,px=0,py=0,last=-1;const clamp=THREE.MathUtils.clamp,local=(v,a,b)=>clamp((v-a)/(b-a),0,1),smooth=(v,a,b)=>THREE.MathUtils.smoothstep(v,a,b),windowA=(v,a,b,c,d)=>smooth(v,a,b)*(1-smooth(v,c,d));
function alphaGroup(o,a){const show=a>.005;o.visible=show;if(!show)return;o.traverse(x=>{if(x.material){const ms=Array.isArray(x.material)?x.material:[x.material];ms.forEach(m=>{if(m.userData.baseOpacity==null)m.userData.baseOpacity=m.opacity==null?1:m.opacity;m.transparent=m.transparent||a<.999;m.opacity=m.userData.baseOpacity*a})}})}
function scrollProgress(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);target=clamp((scrollY||0)/max,0,1)}
function sceneIndex(v){for(let i=0;i<ranges.length;i++)if(v<ranges[i])return i;return 6}
function updateWorld(t){const earthA=1-smooth(p,.26,.34);alphaGroup(earth.group,earthA);earth.group.position.x=-smooth(p,.25,.34)*(mobile()?10:14);earth.group.position.y=THREE.MathUtils.lerp(mobile()?-1.7:-.7,mobile()?-2.2:-1.2,local(p,.08,.25));earth.earth.rotation.y=-1.4+t*.00004+p*.65;earth.clouds.rotation.y=-1.32-t*.00002+p*.42;earth.network.rotation.y=p*.9+t*.000025;
 const coreA=windowA(p,.21,.27,.47,.53);alphaGroup(core.group,coreA);const cp=local(p,.25,.45);core.group.rotation.y=.2+t*.00011+cp*.35;if(core.inner){core.inner.rotation.x=t*.00022;core.inner.rotation.y=-t*.00018}core.components?.forEach((m,i)=>{const e=smooth(cp,.18,.72);m.position.copy(m.userData.base).multiplyScalar(.44+e*.58);m.rotation.y=e*(i%2?-.16:.14)});
 const portalA=windowA(p,.4,.46,.62,.67);alphaGroup(portal,portalA);portal.rotation.z=t*.00007;
 const moonA=windowA(p,.53,.59,.93,.97);alphaGroup(moon.group,moonA);const mp=local(p,.58,.74);moon.rover.position.x=-4.8+mp*7;moon.rover.position.z=2.2-Math.sin(mp*Math.PI)*.55;moon.rover.rotation.y=-.28+mp*.34;moon.rover.traverse(o=>{if(o.userData.wheel)o.rotation.x-=.016});const build=local(p,.74,.91);moon.modules?.forEach((m,i)=>{const q=smooth(build,i*.09,Math.min(1,i*.09+.27));m.scale.setScalar(Math.max(.001,q));m.position.y=(1-q)*-.22});moon.solarArrays?.forEach((a,i)=>{const q=smooth(build,.3+i*.11,.62+i*.11);a.scale.setScalar(Math.max(.001,q));a.rotation.y=(1-q)*(i?-.55:.55)});if(moon.tower)moon.tower.scale.y=Math.max(.001,smooth(build,.48,.82));if(moon.guideLights)moon.guideLights.visible=build>.62;
 const finalA=smooth(p,.89,.95);alphaGroup(finale.group,finalA);if(finale.earth)finale.earth.rotation.y=-1.2+t*.00004+p*.5;if(finale.ring)finale.ring.rotation.z=t*.00006;if(finale.moon)finale.moon.rotation.y=t*.000025;
 route.children.forEach((o,i)=>{if(o.material&&o.material.opacity!=null)o.material.opacity*=.999});gates.forEach((g,i)=>{g.rotation.z=t*.000035*(i%2?1:-1);g.rotation.y=Math.sin(t*.00018+i)*.06});nearField.children.forEach((m,i)=>{m.position.y+=Math.sin(t*.0005+i)*.00025})}
function updateUI(){const idx=sceneIndex(p);if(idx!==last){panels.forEach((el,i)=>el.classList.toggle('active',i===idx));meterScene.textContent=String(idx+1).padStart(2,'0');sceneCode.textContent=labels[idx];last=idx}const pct=(p*100).toFixed(2)+'%';meterFill.style.height=pct;mobileFill.style.width=pct;const pos=camCurve.getPointAt(p);depthValue.textContent=(pos.z>=0?'+':'')+Math.round(pos.z).toString().padStart(3,'0')+' KM';hint.classList.toggle('hide',p>.035);const start=idx?ranges[idx-1]:0,end=ranges[idx],phase=clamp((p-start)/(end-start),0,1),active=panels[idx];if(active){active.style.setProperty('--phase',phase.toFixed(3));active.style.setProperty('--drift',`${((phase-.5)*-16).toFixed(1)}px`)}}
addEventListener('scroll',scrollProgress,{passive:true});addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2},{passive:true});addEventListener('touchmove',e=>{if(e.touches[0]){tx=(e.touches[0].clientX/innerWidth-.5)*2;ty=(e.touches[0].clientY/innerHeight-.5)*2}},{passive:true});addEventListener('resize',()=>{resize();camCurve=new THREE.CatmullRomCurve3(cameraPoints(),false,'catmullrom',.25);lookCurve=new THREE.CatmullRomCurve3(lookPoints(),false,'catmullrom',.25);scrollProgress()},{passive:true});document.addEventListener('visibilitychange',()=>{paused=document.hidden;if(!paused)requestAnimationFrame(frame)});
const look=new THREE.Vector3();let slowFrames=0,lastT=0;function frame(t){if(paused)return;if(lastT&&t-lastT>27)slowFrames++;else slowFrames=Math.max(0,slowFrames-1);lastT=t;if(slowFrames>80&&quality>.72){quality=.72;resize();slowFrames=0}p+=(target-p)*(reduce?1:.075);px+=(tx-px)*(reduce?.1:.035);py+=(ty-py)*(reduce?.1:.035);const pos=camCurve.getPointAt(p),tar=lookCurve.getPointAt(p);camera.position.copy(pos);camera.position.x+=px*(mobile()?.18:.42);camera.position.y-=py*(mobile()?.14:.3);look.copy(tar);look.x+=px*.09;look.y-=py*.07;camera.lookAt(look);updateWorld(t);updateUI();renderer.render(scene,camera);requestAnimationFrame(frame)}scrollProgress();requestAnimationFrame(frame);setTimeout(()=>loader.classList.add('done'),5000);