import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
THREE.Cache.enabled=true;
const mobile=()=>innerWidth<780,canvas=document.getElementById('world'),loader=document.getElementById('loader'),fallback=document.getElementById('fallback');
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile(),powerPreference:'high-performance'})}catch(e){fallback.hidden=false;throw e}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
function resize(){renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile()?1.25:1.55));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=mobile()?58:52;camera.updateProjectionMatrix()} addEventListener('resize',resize,{passive:true});
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020405);scene.fog=new THREE.FogExp2(0x020405,mobile()?.012:.008);const camera=new THREE.PerspectiveCamera(mobile()?58:52,innerWidth/innerHeight,.05,240);resize();
scene.add(new THREE.HemisphereLight(0xa8d6ef,0x050607,1.1));const sun=new THREE.DirectionalLight(0xffffff,5.6);sun.position.set(-6,7,12);scene.add(sun);const rim=new THREE.DirectionalLight(0x72cfff,2.5);rim.position.set(10,-2,-12);scene.add(rim);
const ACID=0xcaff4f,BLUE=0x83d9ff,WHITE=0xeaf7ff,darkMat=new THREE.MeshStandardMaterial({color:0x101619,metalness:.72,roughness:.28}),metal=new THREE.MeshPhysicalMaterial({color:0xd6e1e3,metalness:.88,roughness:.18,clearcoat:1});
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d'),r=g.createRadialGradient(64,64,0,64,64,64);r.addColorStop(0,'#fff');r.addColorStop(.18,'#fff');r.addColorStop(.55,'rgba(255,255,255,.15)');r.addColorStop(1,'rgba(255,255,255,0)');g.fillStyle=r;g.fillRect(0,0,128,128);return new THREE.CanvasTexture(c)}const gtex=glowTexture();
function sprite(size=1,color=ACID,opacity=.65){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:gtex,color,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending}));s.scale.set(size,size,1);return s}
function stars(){const n=mobile()?1300:2400,p=new Float32Array(n*3);for(let i=0;i<n;i++){p[i*3]=(Math.random()-.5)*110;p[i*3+1]=(Math.random()-.5)*72;p[i*3+2]=-Math.random()*180+30}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(p,3));return new THREE.Points(geo,new THREE.PointsMaterial({color:0xa8c2d3,size:mobile()?.035:.045,transparent:true,opacity:.65}))}scene.add(stars());
function tube(a,b,color=ACID,opacity=.5,bow=1.5){const mid=a.clone().add(b).multiplyScalar(.5).normalize().multiplyScalar(Math.max(a.length(),b.length())+bow),curve=new THREE.QuadraticBezierCurve3(a,mid,b);return new THREE.Mesh(new THREE.TubeGeometry(curve,48,.012,5,false),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending}))}
const manager=new THREE.LoadingManager();manager.onProgress=(u,l,t)=>{const e=document.getElementById('loaderPct');if(e)e.textContent=String(Math.round(l/Math.max(1,t)*100)).padStart(2,'0')};manager.onLoad=()=>setTimeout(()=>loader?.classList.add('done'),200);const tl=new THREE.TextureLoader(manager);
// EARTH SYSTEM
const earthSys=new THREE.Group();scene.add(earthSys);const earthMat=new THREE.MeshStandardMaterial({color:0x315c78,roughness:.54,metalness:.03,emissive:0x376d91,emissiveIntensity:.26});const earth=new THREE.Mesh(new THREE.SphereGeometry(3.55,mobile()?64:96,mobile()?44:64),earthMat);earth.rotation.z=-.2;earthSys.add(earth);const cloudMat=new THREE.MeshPhongMaterial({color:0xffffff,transparent:true,opacity:.23,depthWrite:false});const clouds=new THREE.Mesh(new THREE.SphereGeometry(3.59,72,48),cloudMat);earthSys.add(clouds);const atmo=new THREE.Mesh(new THREE.SphereGeometry(3.77,72,48),new THREE.MeshBasicMaterial({color:0x5dbfff,transparent:true,opacity:.13,side:THREE.BackSide,blending:THREE.AdditiveBlending}));earthSys.add(atmo);earthSys.add(sprite(10,0x4db4ff,.15));
tl.load('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg',t=>{t.colorSpace=THREE.SRGBColorSpace;earthMat.map=t;earthMat.needsUpdate=true});tl.load('https://threejs.org/examples/textures/planets/earth_normal_2048.jpg',t=>{earthMat.normalMap=t;earthMat.normalScale.set(.85,.85);earthMat.needsUpdate=true});tl.load('https://threejs.org/examples/textures/planets/earth_lights_2048.png',t=>{t.colorSpace=THREE.SRGBColorSpace;earthMat.emissiveMap=t;earthMat.emissiveIntensity=.75;earthMat.needsUpdate=true});tl.load('https://threejs.org/examples/textures/planets/earth_clouds_1024.png',t=>{t.colorSpace=THREE.SRGBColorSpace;cloudMat.map=t;cloudMat.alphaTest=.03;cloudMat.needsUpdate=true});
const network=new THREE.Group();earthSys.add(network);[4.0,4.35,4.72,5.05].forEach((r,i)=>{const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.012,4,220),new THREE.MeshBasicMaterial({color:i%2?BLUE:ACID,transparent:true,opacity:i===2?.25:.11,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=Math.PI/2+(i-1.5)*.16;ring.rotation.z=i*.35;network.add(ring)});
const coords=[[.9,.15,3.4],[-2.4,1.4,1.9],[2.5,1.4,1.6],[-1.7,-2.2,2.1],[2.3,-1.7,1.7],[-.3,2.8,2.0],[-2.9,-.2,1.1],[1.4,2.1,2.5],[.2,-2.9,1.9]],nodes=[];coords.forEach((v,i)=>{const p=new THREE.Vector3(...v).normalize().multiplyScalar(3.64),m=new THREE.Mesh(new THREE.SphereGeometry(.055,14,10),new THREE.MeshBasicMaterial({color:i%3?ACID:BLUE}));m.position.copy(p);network.add(m);const s=sprite(.46,i%3?ACID:BLUE,.78);s.position.copy(p);network.add(s);nodes.push(p);if(i>0)network.add(tube(nodes[i-1],p,i%2?BLUE:ACID,.36,1.7))});
for(let i=0;i<9;i++){const sat=new THREE.Group();sat.add(new THREE.Mesh(new THREE.BoxGeometry(.22,.16,.2),metal));for(const side of[-1,1]){const panel=new THREE.Mesh(new THREE.BoxGeometry(.58,.018,.22),new THREE.MeshStandardMaterial({color:0x153756,metalness:.3,roughness:.35,emissive:0x0a2235,emissiveIntensity:.6}));panel.position.x=side*.4;sat.add(panel)}const a=i/9*Math.PI*2,r=4.4+(i%3)*.28;sat.position.set(Math.cos(a)*r,Math.sin(a*.72)*2.05,Math.sin(a)*r*.56);sat.lookAt(0,0,0);network.add(sat)}
// AUTONOMY CORE
const core=new THREE.Group();core.position.z=-18;scene.add(core);const coreLens=new THREE.Mesh(new THREE.SphereGeometry(.72,48,32),new THREE.MeshPhysicalMaterial({color:0x182729,metalness:.35,roughness:.06,clearcoat:1,transmission:.12,emissive:0x31530e,emissiveIntensity:.9}));core.add(coreLens);const lensGlow=sprite(3.4,ACID,.24);core.add(lensGlow);const rings=[];[1.35,1.75,2.15].forEach((r,i)=>{const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.08-i*.012,10,160),i===1?metal:new THREE.MeshPhysicalMaterial({color:i?0x33434a:0x12191c,metalness:.9,roughness:.18,clearcoat:1}));ring.rotation.set(i*.65,.35+i*.38,i*.4);core.add(ring);rings.push(ring)});const coreModules=[];for(let i=0;i<8;i++){const a=i/8*Math.PI*2,q=new THREE.Group(),housing=new THREE.Mesh(new THREE.BoxGeometry(.82,.42,.58),i%2?metal:darkMat);q.add(housing);const face=new THREE.Mesh(new THREE.BoxGeometry(.56,.08,.4),new THREE.MeshBasicMaterial({color:i%3?0x6fc8eb:ACID,transparent:true,opacity:.7}));face.position.y=.25;q.add(face);q.userData.angle=a;q.userData.home=new THREE.Vector3(Math.cos(a)*2.65,Math.sin(a)*1.85,Math.sin(a*.7)*.6);q.position.copy(q.userData.home).multiplyScalar(.45);q.lookAt(0,0,0);core.add(q);coreModules.push(q);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),q.userData.home]),new THREE.LineBasicMaterial({color:i%2?BLUE:ACID,transparent:true,opacity:.25}));core.add(line)}for(let i=0;i<18;i++){const fin=new THREE.Mesh(new THREE.BoxGeometry(.06,.8,.22),darkMat);const a=i/18*Math.PI*2;fin.position.set(Math.cos(a)*1.08,Math.sin(a)*1.08,0);fin.rotation.z=a;core.add(fin)}
// TRANSIT VOLUME
const portal=new THREE.Group();portal.position.z=-34;scene.add(portal);const portalRings=[];for(let i=0;i<15;i++){const tor=new THREE.Mesh(new THREE.TorusGeometry(2.2+i*.075,.035,8,120),new THREE.MeshBasicMaterial({color:i%3?BLUE:ACID,transparent:true,opacity:.12+i*.012,depthWrite:false,blending:THREE.AdditiveBlending}));tor.position.z=-i*.48;tor.rotation.x=(i-7)*.015;tor.rotation.y=(i%2?1:-1)*.16;portal.add(tor);portalRings.push(tor)}for(let i=0;i<70;i++){const s=sprite(.12+Math.random()*.2,i%4?BLUE:ACID,.42),a=Math.random()*Math.PI*2,r=1.4+Math.random()*2.2;s.position.set(Math.cos(a)*r,Math.sin(a)*r*.75,-Math.random()*9);portal.add(s)}
// MOON WORLD
const moon=new THREE.Group();moon.position.z=-50;scene.add(moon);const terrainGeo=new THREE.PlaneGeometry(42,40,mobile()?70:120,mobile()?64:100);terrainGeo.rotateX(-Math.PI/2);const pos=terrainGeo.attributes.position;const craters=[[4,-3,4.5],[-7,5,3.3],[10,7,2.8],[-10,-8,5.2],[1,10,2.4]];for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);let y=-2.8+Math.sin(x*.33)*.22+Math.sin(z*.41)*.25+Math.sin((x+z)*.13)*.42;for(const [cx,cz,r] of craters){const d=Math.hypot(x-cx,z-cz);if(d<r)y-=Math.cos(d/r*Math.PI/2)*.75;if(d<r*1.2&&d>r*.82)y+=.16*Math.sin((d-r*.82)/(r*.38)*Math.PI)}pos.setY(i,y)}terrainGeo.computeVertexNormals();const terrain=new THREE.Mesh(terrainGeo,new THREE.MeshStandardMaterial({color:0xa8a69f,roughness:1,metalness:0}));moon.add(terrain);const moonLight=new THREE.DirectionalLight(0xfff4db,5.5);moonLight.position.set(-10,12,7);moon.add(moonLight);
function rover(){const g=new THREE.Group(),accent=new THREE.MeshStandardMaterial({color:ACID,emissive:0x243b08,emissiveIntensity:.65,metalness:.3,roughness:.3});g.add(new THREE.Mesh(new THREE.BoxGeometry(3.2,.36,1.55),metal));const belly=new THREE.Mesh(new THREE.BoxGeometry(2.55,.28,1.2),darkMat);belly.position.y=-.28;g.add(belly);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.15,.86,1.18),accent);cab.position.set(-.75,.62,0);g.add(cab);const glass=new THREE.Mesh(new THREE.BoxGeometry(.56,.34,1.2),new THREE.MeshPhysicalMaterial({color:0x8bc9e8,roughness:.08,transmission:.25,transparent:true,opacity:.8,clearcoat:1}));glass.position.set(-1.34,.7,0);g.add(glass);const mast=new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,1.65,12),metal);mast.position.set(.65,1.2,0);g.add(mast);const head=new THREE.Mesh(new THREE.BoxGeometry(.52,.25,.38),darkMat);head.position.set(.65,2.05,0);g.add(head);for(const side of[-1,1])for(let i=0;i<3;i++){const x=-1.05+i*1.05,w=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.3,28),new THREE.MeshStandardMaterial({color:0x16191a,roughness:.85}));w.rotation.z=Math.PI/2;w.position.set(x,-.48,side*.93);w.userData.wheel=true;g.add(w);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.32,20),accent);hub.rotation.z=Math.PI/2;hub.position.copy(w.position);g.add(hub)}for(const side of[-1,1]){const panel=new THREE.Mesh(new THREE.BoxGeometry(1.15,.05,.62),new THREE.MeshStandardMaterial({color:0x143b5d,metalness:.25,roughness:.35,emissive:0x08283f,emissiveIntensity:.65}));panel.position.set(.65,.55,side*1.04);panel.rotation.x=side*.42;g.add(panel)}return g}const lunarRover=rover();lunarRover.position.set(-6,-2,4);lunarRover.scale.setScalar(1.08);moon.add(lunarRover);
// construction site
const site=new THREE.Group();site.position.set(3,-2.35,-5);moon.add(site);const modules=[],solar=[],lights=[];for(let i=0;i<5;i++){const q=new THREE.Group(),base=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.25,.45,40),darkMat);base.position.y=.2;q.add(base);const dome=new THREE.Mesh(new THREE.SphereGeometry(1.12,48,24,0,Math.PI*2,0,Math.PI/2),new THREE.MeshPhysicalMaterial({color:0xe0ddd2,metalness:.15,roughness:.3,clearcoat:.75}));dome.position.y=.42;q.add(dome);const rim2=new THREE.Mesh(new THREE.TorusGeometry(1.12,.055,8,64),new THREE.MeshBasicMaterial({color:ACID}));rim2.rotation.x=Math.PI/2;rim2.position.y=.39;q.add(rim2);q.position.set((i-2)*2.65,0,(i%2)*2.2);q.scale.setScalar(.001);site.add(q);modules.push(q)}for(let i=0;i<4;i++){const p=new THREE.Group(),post=new THREE.Mesh(new THREE.CylinderGeometry(.08,.1,1.8,12),metal);post.position.y=.9;p.add(post);const panel=new THREE.Mesh(new THREE.BoxGeometry(2.5,.06,1.25),new THREE.MeshStandardMaterial({color:0x133b5e,metalness:.2,roughness:.3,emissive:0x09283e,emissiveIntensity:.7}));panel.position.y=1.8;panel.rotation.x=-.28;p.add(panel);p.position.set(-5.2+i*3.4,0,4.3);p.scale.setScalar(.001);site.add(p);solar.push(p)}const tower=new THREE.Group();const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.14,.22,6.2,16),metal);shaft.position.y=3.1;tower.add(shaft);for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.8+i*.22,.03,6,48),new THREE.MeshBasicMaterial({color:i===1?ACID:BLUE}));ring.rotation.x=Math.PI/2;ring.position.y=4.5+i*.55;tower.add(ring)}tower.position.set(-6,0,-1.8);tower.scale.y=.001;site.add(tower);for(let i=0;i<14;i++){const s=sprite(.3,i%3?BLUE:ACID,.55);s.position.set(-7+i,0.35,(i%2?1:-1)*3.2);s.scale.setScalar(.001);site.add(s);lights.push(s)}
// FINALE: moon + earth corridor
const finalGroup=new THREE.Group();finalGroup.position.z=-90;scene.add(finalGroup);const finalEarth=new THREE.Mesh(new THREE.SphereGeometry(4.7,72,48),earthMat.clone());finalEarth.position.set(5,1,0);finalGroup.add(finalEarth);tl.load('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg',t=>{t.colorSpace=THREE.SRGBColorSpace;finalEarth.material.map=t;finalEarth.material.needsUpdate=true});const finalMoon=new THREE.Mesh(new THREE.SphereGeometry(2.1,56,36),new THREE.MeshStandardMaterial({color:0xb7b4ab,roughness:1}));finalMoon.position.set(-5,-1.5,1);finalGroup.add(finalMoon);const corridor=tube(finalMoon.position.clone(),finalEarth.position.clone(),ACID,.52,3.8);finalGroup.add(corridor);for(let i=0;i<9;i++){const q=sprite(.32,i%2?BLUE:ACID,.5);q.position.lerpVectors(finalMoon.position,finalEarth.position,i/8);q.position.y+=Math.sin(i/8*Math.PI)*2.4;finalGroup.add(q)}
const sections=[...document.querySelectorAll('.story-panel')],labels=['01 / EARTH','02 / NETWORK','03 / CORE','04 / TRANSIT','05 / MOON','06 / BUILD','07 / RETURN'],ranges=[.115,.255,.405,.56,.72,.91,1.001];let target=0,p=0,last=-1,paused=false,px=0,py=0,tx=0,ty=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function keys(){if(mobile())return[{p:0,pos:[0,1.3,16.5],look:[0,-1.9,0]},{p:.12,pos:[1,.3,11.5],look:[0,-1.8,0]},{p:.23,pos:[3.1,.1,8.3],look:[1.6,-1.4,1.8]},{p:.30,pos:[.1,.15,-10.2],look:[0,-.1,-18]},{p:.39,pos:[0,.05,-13],look:[0,0,-18]},{p:.49,pos:[0,0,-26],look:[0,0,-34]},{p:.58,pos:[0,.3,-36],look:[0,-.3,-43]},{p:.68,pos:[3,1.2,-43],look:[-1.5,-1.2,-50]},{p:.76,pos:[1.5,2.2,-49],look:[0,-1.5,-54]},{p:.84,pos:[8,3.4,-55],look:[3,-1.1,-55]},{p:.91,pos:[5,1.8,-57],look:[3,-1.4,-54]},{p:.96,pos:[0,2.4,-79],look:[0,0,-90]},{p:1,pos:[0,2.4,-79],look:[0,0,-90]}];return[{p:0,pos:[0,1.2,14.8],look:[0,-.8,0]},{p:.13,pos:[1.7,.2,9.6],look:[0,-1,0]},{p:.23,pos:[3.3,0,7.6],look:[2,-.8,1.6]},{p:.30,pos:[.2,.2,-10],look:[0,0,-18]},{p:.39,pos:[0,.1,-13],look:[0,0,-18]},{p:.49,pos:[0,0,-26],look:[0,0,-34]},{p:.58,pos:[0,.2,-36],look:[0,-.1,-43]},{p:.68,pos:[4,1.4,-43],look:[-1.5,-1.1,-50]},{p:.76,pos:[2.4,2.4,-49],look:[0,-1.4,-54]},{p:.84,pos:[9,3.4,-55],look:[3,-1,-55]},{p:.91,pos:[6,2,-57],look:[3,-1.4,-54]},{p:.96,pos:[0,2.8,-79],look:[0,0,-90]},{p:1,pos:[0,2.8,-79],look:[0,0,-90]}]}
let K=keys();function interp(v){let a=K[0],b=K.at(-1);for(let i=0;i<K.length-1;i++)if(v>=K[i].p&&v<=K[i+1].p){a=K[i];b=K[i+1];break}let q=(v-a.p)/(b.p-a.p);q=q*q*(3-2*q);return{pos:a.pos.map((x,i)=>THREE.MathUtils.lerp(x,b.pos[i],q)),look:a.look.map((x,i)=>THREE.MathUtils.lerp(x,b.look[i],q))}}function local(v,a,b){return THREE.MathUtils.clamp((v-a)/(b-a),0,1)}function idx(v){for(let i=0;i<ranges.length;i++)if(v<ranges[i])return i;return 6}
function setOpacity(o,a){o.traverse(x=>{if(x.material){const ms=Array.isArray(x.material)?x.material:[x.material];ms.forEach(m=>{if(m.userData.o==null)m.userData.o=m.opacity??1;m.transparent=true;m.opacity=m.userData.o*a})}})}
function world(t){const np=local(p,.08,.25),exit=THREE.MathUtils.smoothstep(p,.225,.29);earthSys.position.y=THREE.MathUtils.lerp(mobile()?-1.9:-.8,mobile()?-2.2:-1.25,np);earthSys.position.x=-exit*(mobile()?15:18);earthSys.scale.setScalar(1-exit*.15);earth.rotation.y=-1.45+t*.00004+p*.9;clouds.rotation.y=-1.4-t*.00002+p*.55;network.rotation.y=t*.000025+p;setOpacity(network,1-THREE.MathUtils.smoothstep(p,.215,.275));
const cp=local(p,.255,.43),explode=THREE.MathUtils.smoothstep(cp,.15,.7);rings.forEach((r,i)=>{r.rotation.x+=.001*(i+1);r.rotation.y-=.0007*(i+1)});core.rotation.y=t*.0001;coreModules.forEach((m,i)=>{m.position.copy(m.userData.home).multiplyScalar(.45+explode*.75);m.rotation.z=Math.sin(t*.001+i)*.08*explode});portalRings.forEach((r,i)=>r.rotation.z=t*.00012*(i%2?1:-1)+i*.06);
const mp=local(p,.57,.75);lunarRover.position.x=-6+mp*8.2;lunarRover.position.z=4-Math.sin(mp*Math.PI)*1.2;lunarRover.rotation.y=-.35+mp*.55;lunarRover.children.forEach(o=>{if(o.userData.wheel)o.rotation.x-=.028});
const build=local(p,.735,.91);modules.forEach((m,i)=>{const q=THREE.MathUtils.smoothstep(build,i*.09,i*.09+.3);m.scale.setScalar(Math.max(.001,q));m.position.y=(1-q)*-2.3;m.rotation.y=(1-q)*(i%2?1:-1)*.8});solar.forEach((m,i)=>{const q=THREE.MathUtils.smoothstep(build,.18+i*.08,.48+i*.08);m.scale.setScalar(Math.max(.001,q));m.rotation.y=(1-q)*1.2});tower.scale.y=Math.max(.001,THREE.MathUtils.smoothstep(build,.45,.78));lights.forEach((s,i)=>s.scale.setScalar(THREE.MathUtils.smoothstep(build,.55+i*.015,.8+i*.01)));finalEarth.rotation.y=t*.00005;finalMoon.rotation.y=-t*.00003}
function ui(){const i=idx(p);if(i!==last){sections.forEach((e,n)=>e.classList.toggle('active',n===i));document.getElementById('sceneCode').textContent=labels[i];document.getElementById('meterScene').textContent=String(i+1).padStart(2,'0');last=i}document.getElementById('meterFill').style.height=(p*100)+'%';document.getElementById('mobileFill').style.width=(p*100)+'%';document.getElementById('depthValue').textContent=(interp(p).pos[2]>=0?'+':'')+Math.round(interp(p).pos[2])+' KM';document.getElementById('hint').classList.toggle('hide',p>.035)}function scroll(){target=Math.max(0,Math.min(1,scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)))}addEventListener('scroll',scroll,{passive:true});addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2},{passive:true});addEventListener('resize',()=>{K=keys()},{passive:true});document.addEventListener('visibilitychange',()=>{paused=document.hidden;if(!paused)requestAnimationFrame(frame)});const look=new THREE.Vector3();function frame(t){if(paused)return;p+=(target-p)*(reduce?1:.085);px+=(tx-px)*.04;py+=(ty-py)*.04;const k=interp(p);camera.position.set(k.pos[0]+px*(mobile()?.2:.45),k.pos[1]-py*(mobile()?.16:.32),k.pos[2]);look.set(k.look[0]+px*.12,k.look[1]-py*.1,k.look[2]);camera.lookAt(look);world(t);ui();renderer.render(scene,camera);requestAnimationFrame(frame)}scroll();requestAnimationFrame(frame);setTimeout(()=>loader?.classList.add('done'),5500);