const $=(s,r=document)=>r.querySelector(s);
const state={sound:false,progress:0,lastScene:-1};
window.__orbitalPanX=0;
window.__orbitalPanTarget=0;
const sceneData=[['EARTH','0 KM'],['ORBIT','400 KM'],['LUNAR TRANSIT','384,400 KM'],['MOON','1.28 LIGHT-SECONDS'],['MARS','225M KM'],['JUPITER','5.2 AU'],['SATURN','9.5 AU'],['DEEP SPACE','BEYOND HOME'],['ANOMALY','26,000 LIGHT-YEARS'],['EVENT HORIZON','NO REFERENCE']];
function mountUI(){const ui=document.createElement('div');ui.className='experience-v4';ui.innerHTML=`<div class="mission-telemetry"><span class="mt-stage">DEPARTURE</span><b class="mt-distance">0 KM</b><i></i><span class="mt-home">DISTANCE FROM HOME</span></div><button class="sound-toggle" type="button"><i></i><span>SOUND OFF</span><small>TAP FOR CINEMATIC AUDIO</small></button><div class="swipe-hint">↔ SWIPE TO LOOK</div><div class="phenomena"><span class="ph-label"></span><b class="ph-title"></b></div><div class="anomaly-ui"><span>GRAVITATIONAL ANOMALY</span><b>REFERENCE FRAME UNSTABLE</b><i></i></div><div class="end-card"><small>OBSERVABLE UNIVERSE</small><h2>WE HAVE<br>BARELY LEFT <em>HOME.</em></h2><button type="button">EXPLORE AGAIN ↑</button></div>`;document.body.appendChild(ui);$('.sound-toggle',ui).onclick=async()=>{state.sound=!state.sound;$('.sound-toggle span',ui).textContent=state.sound?'SOUND ON':'SOUND OFF';$('.sound-toggle small',ui).textContent=state.sound?'CINEMATIC FIELD ACTIVE':'TAP FOR CINEMATIC AUDIO';document.documentElement.classList.toggle('sound-on',state.sound);if(state.sound)await startAudio();else if(master&&ctx)master.gain.setTargetAtTime(0,ctx.currentTime,.12);};$('.end-card button',ui).onclick=()=>scrollTo({top:0,behavior:'smooth'});return ui;}const ui=mountUI();
let ctx,master,drone,bass,airGain;
async function startAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!ctx){ctx=new AC();master=ctx.createGain();master.gain.value=0;master.connect(ctx.destination);drone=ctx.createOscillator();bass=ctx.createOscillator();const dg=ctx.createGain(),bg=ctx.createGain();drone.type='sine';drone.frequency.value=58;dg.gain.value=.55;bass.type='triangle';bass.frequency.value=29;bg.gain.value=.32;drone.connect(dg).connect(master);bass.connect(bg).connect(master);drone.start();bass.start();const air=ctx.createOscillator();airGain=ctx.createGain();air.type='sine';air.frequency.value=116;airGain.gain.value=.08;air.connect(airGain).connect(master);air.start();}await ctx.resume();master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setTargetAtTime(.19,ctx.currentTime,.18);}
function sceneIndex(p){return Math.min(9,Math.floor(p*10));}function updateCopy(i){const [name,dist]=sceneData[i];$('.mt-stage',ui).textContent=name;$('.mt-distance',ui).textContent=dist;const ph=$('.phenomena',ui),titles=['ATMOSPHERIC DEPARTURE','ORBITAL RENDEZVOUS','EARTH → MOON','LUNAR HORIZON','DUST WORLD','GAS GIANT','RING PLANE','INTERSTELLAR VOID','LIGHT BENDS HERE','EVENT HORIZON'];$('.ph-label',ui).textContent=String(i+1).padStart(2,'0')+' / '+name;$('.ph-title',ui).textContent=titles[i];if(i!==state.lastScene){ph.classList.remove('flash');requestAnimationFrame(()=>ph.classList.add('flash'));state.lastScene=i;}document.documentElement.dataset.chapter=String(i);}
function update(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),p=Math.min(1,Math.max(0,scrollY/max));state.progress=p;updateCopy(sceneIndex(p));document.documentElement.style.setProperty('--journey',p.toFixed(4));$('.anomaly-ui',ui).classList.toggle('show',p>.84&&p<.975);$('.end-card',ui).classList.toggle('show',p>.987);window.__orbitalPanX+=(window.__orbitalPanTarget-window.__orbitalPanX)*.085;if(ctx&&state.sound){const f=58+p*24+(p>.84?20*(p-.84)/.16:0);drone.frequency.setTargetAtTime(f,ctx.currentTime,.45);bass.frequency.setTargetAtTime(f*.5,ctx.currentTime,.55);master.gain.setTargetAtTime(p>.965?.11:.19,ctx.currentTime,.45);}requestAnimationFrame(update);}requestAnimationFrame(update);
let touchX=0,touchY=0,lastX=0,dragging=false,horizontal=false;addEventListener('touchstart',e=>{if(e.touches.length!==1)return;touchX=lastX=e.touches[0].clientX;touchY=e.touches[0].clientY;dragging=true;horizontal=false;},{passive:true});addEventListener('touchmove',e=>{if(!dragging||e.touches.length!==1)return;const x=e.touches[0].clientX,y=e.touches[0].clientY,dx=x-touchX,dy=y-touchY;if(!horizontal&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.25)horizontal=true;if(horizontal){const step=x-lastX;window.__orbitalPanTarget=Math.max(-1,Math.min(1,window.__orbitalPanTarget-step/180));$('.swipe-hint',ui).classList.add('active');}lastX=x;},{passive:true});addEventListener('touchend',()=>{dragging=false;horizontal=false;setTimeout(()=>$('.swipe-hint',ui).classList.remove('active'),500);},{passive:true});let lastScroll=scrollY;addEventListener('scroll',()=>{if(Math.abs(scrollY-lastScroll)>1){window.__orbitalPanTarget=0;$('.swipe-hint',ui).classList.remove('active');}lastScroll=scrollY;},{passive:true});
let px=0,py=0;addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;px=(e.clientX/innerWidth-.5)*2;py=(e.clientY/innerHeight-.5)*2;document.documentElement.style.setProperty('--px',px.toFixed(3));document.documentElement.style.setProperty('--py',py.toFixed(3));},{passive:true});