import * as THREE from 'three';import{GLTFLoader}from'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
const canvas=document.getElementById('stage'),mobile=innerWidth<780;const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.4));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050607);scene.fog=new THREE.FogExp2(0x050607,.028);const camera=new THREE.PerspectiveCamera(mobile?48:42,innerWidth/innerHeight,.03,120);scene.add(camera);
const world=new THREE.Group();scene.add(world);const floor=new THREE.Mesh(new THREE.PlaneGeometry(80,80),new THREE.MeshPhysicalMaterial({color:0x090a0b,metalness:.65,roughness:.24,clearcoat:.7,clearcoatRoughness:.16}));floor.rotation.x=-Math.PI/2;floor.position.y=-.68;floor.receiveShadow=true;scene.add(floor);
const hemi=new THREE.HemisphereLight(0x53606a,0x050607,.22);scene.add(hemi);const key=new THREE.RectAreaLight(0xffffff,10,7,.42);key.position.set(-1.5,3.2,2.5);key.rotation.set(-.72,-.2,-.1);scene.add(key);const rim=new THREE.RectAreaLight(0x8ab8ff,8,5,.22);rim.position.set(2.6,1.8,-3);rim.rotation.set(.2,2.55,0);scene.add(rim);const strip=new THREE.RectAreaLight(0xffffff,0,12,.08);strip.position.set(0,2.8,0);strip.rotation.x=-Math.PI/2;scene.add(strip);const frontGlow=new THREE.SpotLight(0xe6f4ff,0,16,.35,.75,1.3);frontGlow.position.set(0,.65,4.5);frontGlow.target.position.set(0,.2,0);scene.add(frontGlow,frontGlow.target);
let car=null,carRoot=null,loaded=false;const wheelMeshes=[],paintMeshes=[],lightMeshes=[],glassMeshes=[],cockpitMeshes=[];
new GLTFLoader().load('./assets/bmw_m3_e92.glb',g=>{carRoot=g.scene;const box=new THREE.Box3().setFromObject(carRoot),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);carRoot.position.sub(center);carRoot.position.y+=.03;carRoot.rotation.y=Math.PI;carRoot.traverse(o=>{if(!o.isMesh)return;o.castShadow=!mobile;o.receiveShadow=true;const n=(o.material?.name||'').toLowerCase();if(n.includes('paint'))paintMeshes.push(o);if(n.includes('wheel')||n.includes('tyre')||n.includes('disc')||n.includes('caliper'))wheelMeshes.push(o);if(n.includes('light'))lightMeshes.push(o);if(n.includes('glass'))glassMeshes.push(o);if(n.includes('cockpit')||n.includes('alcantara')||n.includes('lcd'))cockpitMeshes.push(o);if(o.material){o.material.envMapIntensity=1.1;o.material.needsUpdate=true;}});car=new THREE.Group();car.add(carRoot);world.add(car);loaded=true;},undefined,()=>{document.getElementById('missing').hidden=false;});
const tunnel=new THREE.Group();scene.add(tunnel);for(let i=0;i<28;i++){const l=new THREE.Mesh(new THREE.BoxGeometry(.05,.045,8),new THREE.MeshBasicMaterial({color:i%3===0?0xbfd9ff:0xf2f2ee,transparent:true,opacity:.1}));l.position.set((i%2?1:-1)*(3.2+(i%5)*.25),1.25,-i*3);l.rotation.z=(i%2?1:-1)*.28;tunnel.add(l);}tunnel.visible=false;
const V=(x,y,z)=>new THREE.Vector3(x,y,z);const shots=[
{p:0,pos:[5.8,1.7,7.7],look:[0,.15,0],fov:38,carY:0,light:0},
{p:.10,pos:[4.6,1.25,5.1],look:[.2,.22,.1],fov:36,carY:.05,light:.5},
{p:.20,pos:[3.9,.95,4.05],look:[.15,.18,.45],fov:34,carY:.08,light:1},
{p:.29,pos:[2.55,.45,2.25],look:[.78,-.05,.92],fov:31,carY:.11,light:.72},
{p:.37,pos:[3.85,.72,.25],look:[0,.12,0],fov:36,carY:.22,light:.85},
{p:.47,pos:[1.85,1.12,-2.5],look:[-.25,.48,-.25],fov:32,carY:.3,light:.65},
{p:.57,pos:[-.25,1.48,3.8],look:[0,.38,.2],fov:34,carY:.44,light:.85},
{p:.68,pos:[5.4,1.55,5.2],look:[0,.2,0],fov:40,carY:.68,light:1},
{p:.78,pos:[-5.3,1.25,4.9],look:[0,.15,0],fov:41,carY:1.0,light:1},
{p:.88,pos:[0,1.08,6.9],look:[0,.1,0],fov:44,carY:1.0,light:.55},
{p:1,pos:[5.7,1.5,6.2],look:[0,.18,0],fov:38,carY:1.18,light:.82}];
function ease(x){x=THREE.MathUtils.clamp(x,0,1);return x*x*(3-2*x)}function sample(p){let a=shots[0],b=shots.at(-1);for(let i=0;i<shots.length-1;i++)if(p>=shots[i].p&&p<=shots[i+1].p){a=shots[i];b=shots[i+1];break}const t=ease((p-a.p)/(b.p-a.p));return{pos:V(...a.pos).lerp(V(...b.pos),t),look:V(...a.look).lerp(V(...b.look),t),fov:THREE.MathUtils.lerp(a.fov,b.fov,t),carY:THREE.MathUtils.lerp(a.carY,b.carY,t),light:THREE.MathUtils.lerp(a.light,b.light,t)}}
let target=0,progress=0,lastScene=-1;const chapters=[...document.querySelectorAll('.chapter')],bar=document.querySelector('.progress i');function read(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);target=THREE.MathUtils.clamp(scrollY/max,0,1)}addEventListener('scroll',read,{passive:true});read();
const camPos=V(...shots[0].pos),camLook=V(...shots[0].look),clock=new THREE.Clock();function frame(){const dt=Math.min(.04,clock.getDelta());progress+=(target-progress)*(mobile?.045:.035);const s=sample(progress);camPos.lerp(s.pos,1-Math.pow(.002,dt));camLook.lerp(s.look,1-Math.pow(.003,dt));camera.position.copy(camPos);camera.lookAt(camLook);camera.fov+=((s.fov)-(camera.fov))*.06;camera.updateProjectionMatrix();
if(car){car.rotation.y+=((s.carY)-(car.rotation.y))*.045;car.position.y=Math.sin(progress*Math.PI)*.015;}
strip.intensity=11*s.light;key.intensity=4+8*s.light;rim.intensity=2+7*s.light;frontGlow.intensity=progress>.08&&progress<.25?6*(1-Math.abs(progress-.165)/.085):0;
const motion=ease((progress-.72)/.18);tunnel.visible=motion>.02;tunnel.position.z=(performance.now()*.003*motion)%3;tunnel.children.forEach((l,i)=>{l.material.opacity=.04+motion*.18*(i%4===0?1:.55)});floor.material.roughness=.24+motion*.18;
if(paintMeshes.length)paintMeshes.forEach(m=>{if(m.material)m.material.envMapIntensity=1.1+s.light*.7});if(lightMeshes.length)lightMeshes.forEach(m=>{if(m.material){m.material.emissiveIntensity=progress>.08&&progress<.26?1.8:progress>.72?.55:0}});
bar.style.width=(progress*100)+'%';const idx=Math.min(7,Math.floor(progress*8));if(idx!==lastScene){chapters.forEach((c,i)=>c.classList.toggle('active',i===idx));lastScene=idx}renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<780?1:1.4));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});