(()=>{const UID='f816eaa10c2b4c46aef3118f31beea24',iframe=document.getElementById('api-frame'),gesture=document.getElementById('gestureLayer'),gestureTip=document.getElementById('gestureTip'),loading=document.querySelector('.loading'),bar=document.querySelector('.progress i'),chapters=[...document.querySelectorAll('.chapter')],shotName=document.getElementById('shotName'),flash=document.querySelector('.scene-flash');let api=null,ready=false,base=null,lastScene=-1,targetP=0,currentP=0,lastCameraPush=0,panTarget=0,panCurrent=0,startX=0,startY=0,dragging=false,horizontal=false,interacted=false;const client=new Sketchfab('1.12.1',iframe);client.init(UID,{autostart:1,camera:0,scrollwheel:0,dnt:1,annotations_visible:0,ui_hint:0,ui_controls:0,ui_infos:0,ui_settings:0,ui_inspector:0,success(a){api=a;api.start();api.addEventListener('viewerready',()=>{api.getCameraLookAt((err,c)=>{if(err||!c)return;base=c;ready=true;loading.classList.add('ready');api.setUserInteraction(false);api.setCameraEasing('easeInOutQuad');});});},error(){loading.querySelector('b').textContent='VIEWER COULD NOT START';}});const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,ease=t=>t*t*(3-2*t),easeC=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;function rotateZ(v,a){const c=Math.cos(a),s=Math.sin(a);return[v[0]*c-v[1]*s,v[0]*s+v[1]*c,v[2]]}function norm(v){const l=Math.hypot(v[0],v[1],v[2])||1;return[v[0]/l,v[1]/l,v[2]/l]}function add(a,b,s=1){return[a[0]+b[0]*s,a[1]+b[1]*s,a[2]+b[2]*s]}
const shots=[
{p:0,yaw:-.48,r:1.72,z:.16,tx:-.03,tz:.03,fov:42},{p:.075,yaw:-.48,r:1.68,z:.15,tx:-.03,tz:.03,fov:41},
{p:.105,yaw:-.12,r:1.18,z:.00,tx:.00,tz:-.01,fov:31},{p:.205,yaw:-.12,r:1.16,z:.00,tx:.00,tz:-.01,fov:31},
{p:.235,yaw:.46,r:.46,z:-.13,tx:.35,tz:-.18,fov:23},{p:.335,yaw:.46,r:.46,z:-.13,tx:.35,tz:-.18,fov:23},
{p:.355,yaw:1.54,r:1.08,z:.00,tx:-.30,tz:-.02,fov:36},{p:.455,yaw:1.54,r:1.08,z:.00,tx:.28,tz:-.02,fov:36},
{p:.485,yaw:2.74,r:.53,z:.22,tx:-.10,tz:.19,fov:25},{p:.595,yaw:2.74,r:.53,z:.22,tx:-.10,tz:.19,fov:25},
{p:.615,yaw:.74,r:1.64,z:.14,tx:0,tz:.03,fov:42},{p:.725,yaw:.74,r:1.62,z:.14,tx:0,tz:.03,fov:42},
{p:.735,yaw:-.70,r:1.28,z:.02,tx:.02,tz:.00,fov:43},{p:.785,yaw:-.70,r:1.24,z:.02,tx:.02,tz:.00,fov:43},{p:.865,yaw:-.58,r:1.14,z:.02,tx:.03,tz:.00,fov:44},
{p:.90,yaw:2.46,r:1.48,z:.10,tx:0,tz:.02,fov:40},{p:1,yaw:2.46,r:1.48,z:.10,tx:0,tz:.02,fov:40}];
function sample(p){let a=shots[0],b=shots.at(-1);for(let i=0;i<shots.length-1;i++){if(p>=shots[i].p&&p<=shots[i+1].p){a=shots[i];b=shots[i+1];break}}const span=Math.max(.0001,b.p-a.p),raw=clamp((p-a.p)/span,0,1),t=easeC(raw),o={};for(const k of['yaw','r','z','tx','tz','fov'])o[k]=mix(a[k],b[k],t);o.yaw+=panCurrent*.60;return o}
function cameraFor(s){const t=base.target,v=[base.position[0]-t[0],base.position[1]-t[1],base.position[2]-t[2]],R=Math.hypot(...v),dir=norm(v),flat=norm([dir[0],dir[1],0]),right=norm([-flat[1],flat[0],0]),rot=rotateZ(v,s.yaw),pos=[t[0]+rot[0]*s.r,t[1]+rot[1]*s.r,t[2]+rot[2]*s.r+R*s.z],target=add(add(t,right,R*s.tx),[0,0,1],R*s.tz);return{pos,target,fov:s.fov}}
const sceneCuts=[0,.105,.235,.355,.485,.615,.735,.90,1],sceneNames=['01 / WAKE','02 / FACE','03 / CONTACT','04 / PROFILE','05 / COCKPIT','06 / HERO','07 / MOTION','08 / AFTER'];function sceneFor(p){for(let i=sceneCuts.length-2;i>=0;i--)if(p>=sceneCuts[i])return i;return 0}function localFor(p,i){const a=sceneCuts[i],b=sceneCuts[i+1]||1;return clamp((p-a)/(b-a),0,1)}function hideHint(){if(interacted)return;interacted=true;gestureTip?.classList.add('hide')}function read(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);targetP=clamp(scrollY/max,0,1);panTarget=0;if(scrollY>12)hideHint()}addEventListener('scroll',read,{passive:true});read();gesture.addEventListener('touchstart',e=>{hideHint();if(!e.touches[0])return;startX=e.touches[0].clientX;startY=e.touches[0].clientY;dragging=true;horizontal=false},{passive:true});gesture.addEventListener('touchmove',e=>{if(!dragging||!e.touches[0])return;const dx=e.touches[0].clientX-startX,dy=e.touches[0].clientY-startY;if(!horizontal&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.2)horizontal=true;if(horizontal){e.preventDefault();panTarget=clamp(dx/innerWidth*1.05,-.55,.55)}},{passive:false});gesture.addEventListener('touchend',()=>{dragging=false;horizontal=false;panTarget*=.45},{passive:true});gesture.addEventListener('pointerdown',e=>{hideHint();if(e.pointerType==='touch')return;startX=e.clientX;dragging=true;gesture.setPointerCapture?.(e.pointerId)});gesture.addEventListener('pointermove',e=>{if(!dragging||e.pointerType==='touch')return;panTarget=clamp((e.clientX-startX)/innerWidth,-.55,.55)});gesture.addEventListener('pointerup',()=>{dragging=false;panTarget*=.45});
function hitFlash(){if(!flash)return;flash.classList.remove('hit');void flash.offsetWidth;flash.classList.add('hit')}
function frame(t){currentP+=(targetP-currentP)*.052;panCurrent+=(panTarget-panCurrent)*.11;if(!dragging)panTarget*=.86;document.documentElement.style.setProperty('--motion',currentP.toFixed(4));const idx=sceneFor(targetP),local=localFor(targetP,idx);document.documentElement.style.setProperty('--local',local.toFixed(4));bar.style.width=(currentP*100)+'%';if(idx!==lastScene){document.documentElement.dataset.scene=idx;chapters.forEach((c,i)=>c.classList.toggle('active',i===idx));shotName.textContent=sceneNames[idx];hitFlash();lastScene=idx}if(ready&&t-lastCameraPush>70){const c=cameraFor(sample(currentP));api.setCameraLookAt(c.pos,c.target,.14);api.setFov(c.fov);lastCameraPush=t}requestAnimationFrame(frame)}document.documentElement.dataset.scene='0';requestAnimationFrame(frame);})();