import * as THREE from 'three';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

const $=id=>document.getElementById(id),canvas=$('stage'),loader=$('loader'),pct=$('loaderPct'),gesture=$('gesture'),progress=$('progressBar'),sceneCode=$('sceneCode'),sceneName=$('sceneName'),rpm=$('rpmValue'),giant=$('giantNumber'),micro=$('microCopy'),flash=$('flash'),chapters=[...document.querySelectorAll('.chapter')];
const MOBILE=matchMedia('(max-width:780px)').matches;
const renderer=new THREE.WebGLRenderer({canvas,antialias:!MOBILE,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,MOBILE?1.2:1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.82;renderer.shadowMap.enabled=!MOBILE;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x040404);scene.fog=new THREE.FogExp2(0x050505,.018);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.05,150);camera.position.set(4.6,1.4,-6);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
scene.add(new THREE.HemisphereLight(0x6e86a0,0x050505,.38));const key=new THREE.DirectionalLight(0xffffff,4.5);key.position.set(-4,7,-5);scene.add(key);const rim=new THREE.DirectionalLight(0x87bfff,3.5);rim.position.set(5,3,4);scene.add(rim);const red=new THREE.PointLight(0xff2b18,0,13,2);red.position.set(-2,.8,-1);scene.add(red);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(60,120),new THREE.MeshStandardMaterial({color:0x080808,roughness:.42,metalness:.22}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=!MOBILE;scene.add(floor);
const car=new THREE.Group();scene.add(car);const paint=new THREE.MeshPhysicalMaterial({color:0xe7e7e4,metalness:.72,roughness:.2,clearcoat:1,clearcoatRoughness:.12});const black=new THREE.MeshStandardMaterial({color:0x090909,metalness:.55,roughness:.28});const glass=new THREE.MeshPhysicalMaterial({color:0x101820,metalness:.05,roughness:.08,transmission:.35,transparent:true,opacity:.72});const redMat=new THREE.MeshStandardMaterial({color:0xff2515,emissive:0xff1808,emissiveIntensity:2.5});const whiteMat=new THREE.MeshStandardMaterial({color:0xeef7ff,emissive:0xdcefff,emissiveIntensity:2});
function mesh(g,m,p=[0,0,0],r=[0,0,0]){const o=new THREE.Mesh(g,m);o.position.set(...p);o.rotation.set(...r);o.castShadow=!MOBILE;o.receiveShadow=!MOBILE;car.add(o);return o}
mesh(new RoundedBoxGeometry(1.82,.46,4.45,5,.18),paint,[0,.57,0]);mesh(new RoundedBoxGeometry(1.72,.22,2.05,5,.16),paint,[0,.89,-.35]);mesh(new RoundedBoxGeometry(1.42,.46,1.95,5,.17),glass,[0,1.12,.12]);mesh(new RoundedBoxGeometry(1.72,.13,1.28,4,.08),paint,[0,.9,-1.45]);mesh(new RoundedBoxGeometry(1.76,.18,.82,4,.08),paint,[0,.72,1.72]);mesh(new RoundedBoxGeometry(1.7,.1,.16,3,.04),black,[0,.5,-2.18]);
for(const x of[-.93,.93]){for(const z of[-1.42,1.42]){const wheel=new THREE.Group();wheel.position.set(x,.43,z);wheel.rotation.z=Math.PI/2;const tire=new THREE.Mesh(new THREE.TorusGeometry(.39,.13,18,40),black);wheel.add(tire);const rimG=new THREE.Mesh(new THREE.CylinderGeometry(.26,.26,.1,18),new THREE.MeshStandardMaterial({color:0x333333,metalness:.9,roughness:.2}));rimG.rotation.z=Math.PI/2;wheel.add(rimG);for(let a=0;a<5;a++){const spoke=new THREE.Mesh(new THREE.BoxGeometry(.05,.46,.035),new THREE.MeshStandardMaterial({color:0x666,metalness:.9,roughness:.2}));spoke.rotation.z=a*Math.PI/5;wheel.add(spoke)}car.add(wheel)}}
for(const x of[-.52,.52])mesh(new RoundedBoxGeometry(.42,.14,.04,3,.03),whiteMat,[x,.67,-2.24]);for(const x of[-.58,.58])mesh(new RoundedBoxGeometry(.46,.13,.04,3,.03),redMat,[x,.72,2.19]);
for(const x of[-.22,.22])mesh(new RoundedBoxGeometry(.28,.22,.04,3,.04),black,[x,.55,-2.23]);mesh(new THREE.BoxGeometry(1.3,.05,.35),black,[0,1.05,2.0],[.08,0,0]);
car.scale.setScalar(1.03);
const env={studio:new THREE.Group(),grid:new THREE.Group(),track:new THREE.Group()};scene.add(env.studio,env.grid,env.track);const wall=new THREE.Mesh(new THREE.PlaneGeometry(26,9),new THREE.MeshStandardMaterial({color:0x0a0a0a,roughness:.75}));wall.position.set(0,3.8,7);wall.rotation.y=Math.PI;env.studio.add(wall);for(const x of[-4.8,4.8]){const s=new THREE.Mesh(new THREE.PlaneGeometry(.8,5),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.12,side:THREE.DoubleSide}));s.position.set(x,3,0);s.rotation.y=Math.PI/2;env.studio.add(s)}for(let z=-8;z<8;z+=2){const l=new THREE.Mesh(new THREE.PlaneGeometry(5,.035),new THREE.MeshBasicMaterial({color:z%4?0x777777:0xff2b18,transparent:true,opacity:.35}));l.rotation.x=-Math.PI/2;l.position.set(0,.008,z);env.grid.add(l)}const road=new THREE.Mesh(new THREE.PlaneGeometry(11,100),new THREE.MeshStandardMaterial({color:0x0b0b0b,roughness:.9}));road.rotation.x=-Math.PI/2;env.track.add(road);env.dashes=[];for(let z=-45;z<45;z+=5)for(const x of[-2.25,2.25]){const d=new THREE.Mesh(new THREE.PlaneGeometry(.1,2),new THREE.MeshBasicMaterial({color:0xd8d5ce}));d.rotation.x=-Math.PI/2;d.position.set(x,.01,z);env.track.add(d);env.dashes.push(d)}
const names=['IGNITION','FRONT ATTACK','BRAKE ZONE','SIDE DRAFT','AERO','HERO GRID','FULL ATTACK','AFTERMATH'],micros=['S65 // 4.0 V8','FRONT // ATTACK','100 → 0 // COMMIT','SIDE // DRAFT','WAKE // AERO','GRID // 001','8400 // REDLINE','HEAT // OFF'],cuts=[0,.12,.25,.38,.51,.64,.76,.9,1];const shots=[[[4.5,1.3,-5.8],[0,.68,0],43],[[3.6,.9,-4.7],[0,.62,-.9],38],[[-1.7,.62,-2.05],[-.85,.43,-1.4],29],[[-5.2,1,-1],[0,.62,-.2],39],[[4.2,1.2,4.5],[0,.66,.8],39],[[4.7,1.8,-6],[0,.7,0],42],[[3.1,1.02,-5.5],[0,.62,-.5],42],[[-4.5,1.45,5.3],[0,.66,.5],43]];let tp=0,sp=0,current=-1,drag=0,targetDrag=0,startX=0,dragging=false,lastScroll=0;
function idx(p){for(let i=7;i>=0;i--)if(p>=cuts[i])return i;return 0}function local(p,i){return THREE.MathUtils.clamp((p-cuts[i])/(cuts[i+1]-cuts[i]),0,1)}
function updateScene(i,l){if(i!==current){current=i;chapters.forEach((c,n)=>c.classList.toggle('active',n===i));sceneCode.textContent=String(i+1).padStart(2,'0');sceneName.textContent=names[i];giant.textContent=String(i+1).padStart(2,'0');micro.textContent=micros[i];flash.classList.remove('hit');void flash.offsetWidth;flash.classList.add('hit')}env.studio.visible=i!==6;env.grid.visible=i===1||i===5;env.track.visible=i===6;key.intensity=[1.2,5.5,3.8,4.6,3.4,6,4.3,2.2][i];rim.intensity=[2,4.2,2.6,5.4,4.8,5,3.2,3.5][i];red.intensity=i===2?14*Math.sin(Math.PI*l):i===7?3:0;renderer.toneMappingExposure=[.55,.92,.8,.84,.8,1,.84,.68][i];scene.fog.density=i===6?.03:.016}
function cameraShot(i,l){let p=[...shots[i][0]],t=[...shots[i][1]],f=shots[i][2];if(i===3){p=[-5.2,1,-1.5+3*l];t=[0,.62,-1+2*l]}if(i===6)p=[3.1-.4*l,1.02,-5.5+.25*l];const pos=new THREE.Vector3(...p),tar=new THREE.Vector3(...t);const dir=new THREE.Vector3().subVectors(tar,pos).normalize(),right=new THREE.Vector3().crossVectors(dir,new THREE.Vector3(0,1,0)).normalize();tar.addScaledVector(right,drag*.9);camera.position.lerp(pos,.095);const q=new THREE.Quaternion().setFromRotationMatrix(new THREE.Matrix4().lookAt(camera.position,tar,new THREE.Vector3(0,1,0)));camera.quaternion.slerp(q,.11);camera.fov+=(f-camera.fov)*.08;camera.updateProjectionMatrix()}
function read(){const m=Math.max(1,document.documentElement.scrollHeight-innerHeight);tp=THREE.MathUtils.clamp(scrollY/m,0,1);targetDrag=0;if(scrollY!==lastScroll){gesture.classList.add('hide');lastScroll=scrollY}}addEventListener('scroll',read,{passive:true});read();canvas.addEventListener('pointerdown',e=>{gesture.classList.add('hide');dragging=true;startX=e.clientX});canvas.addEventListener('pointermove',e=>{if(dragging)targetDrag=THREE.MathUtils.clamp((e.clientX-startX)/innerWidth,-.8,.8)});addEventListener('pointerup',()=>{dragging=false;targetDrag*=.4});canvas.addEventListener('touchstart',()=>gesture.classList.add('hide'),{passive:true});
pct.textContent='100';loader.querySelector('b').textContent='LOCAL GRID READY';setTimeout(()=>loader.classList.add('done'),220);
const clock=new THREE.Clock();let last=0;function loop(t){requestAnimationFrame(loop);if(MOBILE&&t-last<30)return;last=t;const dt=Math.min(.05,clock.getDelta());sp+=(tp-sp)*.065;drag+=(targetDrag-drag)*.12;if(!dragging)targetDrag*=.9;progress.style.width=(sp*100)+'%';document.documentElement.style.setProperty('--p',sp.toFixed(4));const i=idx(sp),l=local(sp,i);updateScene(i,l);cameraShot(i,l);rpm.textContent=String(Math.round(([800,3400,6100,5200,7000,7600,8400,1200][i]+(i===6?1200*l:0))/50)*50).padStart(4,'0');car.rotation.y+=(0-car.rotation.y)*.07;if(i===0)car.rotation.y=-.06+.05*l;if(i===5)car.rotation.y=.08*Math.sin(l*Math.PI);if(i===6){car.position.y=Math.sin(t*.024)*.006;env.dashes.forEach(d=>{d.position.z+=dt*(22+38*l);if(d.position.z>22)d.position.z-=90})}else car.position.y=0;renderer.render(scene,camera)}requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width:780px)').matches?1.2:1.6))},{passive:true});