import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

const canvas=document.getElementById('stage'), loaderEl=document.getElementById('loader'), loaderPct=document.getElementById('loaderPct');
const chapters=[...document.querySelectorAll('.chapter')], progressBar=document.getElementById('progressBar'), sceneCode=document.getElementById('sceneCode'), sceneName=document.getElementById('sceneName'), rpmValue=document.getElementById('rpmValue'), giantNumber=document.getElementById('giantNumber'), microCopy=document.getElementById('microCopy'), gesture=document.getElementById('gesture'), flash=document.getElementById('flash');
const MOBILE=matchMedia('(max-width:780px)').matches;
const renderer=new THREE.WebGLRenderer({canvas,antialias:!MOBILE,alpha:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,MOBILE?1.25:1.7)); renderer.setSize(innerWidth,innerHeight,false); renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=.95; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.shadowMap.enabled=!MOBILE; renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x050505); scene.fog=new THREE.FogExp2(0x050505,.018);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.05,140); camera.position.set(5,2.2,-7);
const pmrem=new THREE.PMREMGenerator(renderer); scene.environment=pmrem.fromScene(new RoomEnvironment(),.03).texture;
const carRoot=new THREE.Group(); scene.add(carRoot);
scene.add(new THREE.HemisphereLight(0x74869a,0x080808,.18));
const key=new THREE.DirectionalLight(0xffffff,4.8); key.position.set(-4,8,-5); key.castShadow=!MOBILE; key.shadow.mapSize.set(1024,1024); scene.add(key);
const rim=new THREE.DirectionalLight(0x9bc9ff,3.2); rim.position.set(5,4,4); scene.add(rim);
const redKick=new THREE.PointLight(0xff2b18,0,12,2); redKick.position.set(-2,.8,-1); scene.add(redKick);
const amberKick=new THREE.PointLight(0xffa000,0,12,2); amberKick.position.set(2,1.2,1); scene.add(amberKick);
const floorMat=new THREE.MeshStandardMaterial({color:0x080808,roughness:.45,metalness:.25});
const floor=new THREE.Mesh(new THREE.PlaneGeometry(80,120),floorMat); floor.rotation.x=-Math.PI/2; floor.position.y=0; floor.receiveShadow=!MOBILE; scene.add(floor);
function mat(color,emissive=0,opacity=1){return new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:emissive?2:0,roughness:.36,metalness:.25,transparent:opacity<1,opacity,depthWrite:opacity>.7})}
function basic(color,opacity=1){return new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:false,side:THREE.DoubleSide})}
const env={};
function makeEnvironment(){
  env.studio=new THREE.Group();
  const wall=new THREE.Mesh(new THREE.PlaneGeometry(30,10),new THREE.MeshStandardMaterial({color:0x090909,roughness:.7,metalness:.05})); wall.position.set(0,4,8); wall.rotation.y=Math.PI; env.studio.add(wall);
  for(const x of[-5.4,5.4]){const soft=new THREE.Mesh(new THREE.PlaneGeometry(1.1,6),basic(0xf6f3e8,.13));soft.position.set(x,3.6,1);soft.rotation.y=x<0?Math.PI/2:-Math.PI/2;env.studio.add(soft)}
  const top=new THREE.Mesh(new THREE.PlaneGeometry(7,.22),basic(0xffffff,.18));top.position.set(0,5.4,-1);top.rotation.x=Math.PI/2;env.studio.add(top);scene.add(env.studio);
  env.grid=new THREE.Group();
  for(let z=-7;z<=7;z+=2.4){const stripe=new THREE.Mesh(new THREE.PlaneGeometry(4.8,.055),basic(z%4.8===0?0xff2b18:0xe9e7df,.38));stripe.rotation.x=-Math.PI/2;stripe.position.set(0,.008,z);env.grid.add(stripe)}
  for(const x of[-2.6,2.6]){const edge=new THREE.Mesh(new THREE.PlaneGeometry(.055,18),basic(0xff2b18,.42));edge.rotation.x=-Math.PI/2;edge.position.set(x,.009,0);env.grid.add(edge)}scene.add(env.grid);
  env.platform=new THREE.Group();
  const p=new THREE.Mesh(new THREE.CylinderGeometry(3.35,3.5,.11,64),new THREE.MeshStandardMaterial({color:0x0b0b0b,roughness:.25,metalness:.65}));p.position.y=.055;p.receiveShadow=!MOBILE;env.platform.add(p);
  const ring=new THREE.Mesh(new THREE.TorusGeometry(3.05,.025,12,100),basic(0xff2b18,.65));ring.rotation.x=Math.PI/2;ring.position.y=.12;env.platform.add(ring);scene.add(env.platform);
  env.track=new THREE.Group();
  const road=new THREE.Mesh(new THREE.PlaneGeometry(12,110),new THREE.MeshStandardMaterial({color:0x101010,roughness:.82,metalness:.03}));road.rotation.x=-Math.PI/2;road.position.y=.012;env.track.add(road);
  env.dashes=[];for(let z=-45;z<45;z+=5){for(const x of[-2.2,2.2]){const d=new THREE.Mesh(new THREE.PlaneGeometry(.11,2),basic(0xe8e2d8,.65));d.rotation.x=-Math.PI/2;d.position.set(x,.018,z);env.track.add(d);env.dashes.push(d)}}
  for(const x of[-5.3,5.3]){const barrier=new THREE.Mesh(new THREE.BoxGeometry(.22,1.25,90),new THREE.MeshStandardMaterial({color:0x161616,roughness:.55,metalness:.45}));barrier.position.set(x,.63,0);env.track.add(barrier)}
  env.gantries=[];for(let z=-38;z<35;z+=11){const g=new THREE.Group();for(const x of[-5,5]){const post=new THREE.Mesh(new THREE.BoxGeometry(.15,4,.15),mat(0x242424));post.position.set(x,2,z);g.add(post)}const beam=new THREE.Mesh(new THREE.BoxGeometry(10.2,.16,.18),mat(0x242424));beam.position.set(0,3.75,z);g.add(beam);const light=new THREE.Mesh(new THREE.BoxGeometry(4.2,.06,.2),basic(0xffb000,.9));light.position.set(0,3.63,z-.02);g.add(light);env.track.add(g);env.gantries.push(g)}scene.add(env.track);
  env.brakes=new THREE.Group();for(const [x,z] of[[-.91,-1.48],[.91,-1.48]]){const disc=new THREE.Mesh(new THREE.CircleGeometry(.28,40),basic(0xff351d,0));disc.position.set(x,.42,z-.03);disc.rotation.y=0;env.brakes.add(disc)}scene.add(env.brakes);
  env.lights=new THREE.Group();
  function glow(c,s){const cv=document.createElement('canvas');cv.width=cv.height=128;const ct=cv.getContext('2d'),gr=ct.createRadialGradient(64,64,0,64,64,64);gr.addColorStop(0,c);gr.addColorStop(.18,c);gr.addColorStop(1,'rgba(0,0,0,0)');ct.fillStyle=gr;ct.fillRect(0,0,128,128);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv),transparent:true,depthWrite:false,opacity:0}));sp.scale.set(s,s,s);return sp}
  env.headGlow=[glow('rgba(225,242,255,1)',.65),glow('rgba(225,242,255,1)',.65)];env.headGlow[0].position.set(-.56,.62,-2.27);env.headGlow[1].position.set(.56,.62,-2.27);env.headGlow.forEach(s=>env.lights.add(s));
  env.tailGlow=[glow('rgba(255,35,20,1)',.55),glow('rgba(255,35,20,1)',.55)];env.tailGlow[0].position.set(-.62,.68,2.05);env.tailGlow[1].position.set(.62,.68,2.05);env.tailGlow.forEach(s=>env.lights.add(s));scene.add(env.lights);
  const h1=new THREE.SpotLight(0xdcecff,0,24,Math.PI/7,.55,1.8),h2=h1.clone();h1.position.set(-.56,.65,-2.2);h2.position.set(.56,.65,-2.2);h1.target.position.set(-.56,.25,-12);h2.target.position.set(.56,.25,-12);scene.add(h1,h2,h1.target,h2.target);env.headSpots=[h1,h2];
  setEnv(0,0);
}
makeEnvironment();
const sceneNames=['IGNITION','FRONT ATTACK','BRAKE ZONE','SIDE DRAFT','AERO','HERO GRID','FULL ATTACK','AFTERMATH'];
const micro=['S65 // 4.0 V8','FRONT // ATTACK','100 → 0 // COMMIT','SIDE // DRAFT','WAKE // AERO','GRID // 001','8400 // REDLINE','HEAT // OFF'];
const cuts=[0,.12,.25,.38,.51,.64,.76,.90,1];
let currentScene=-1,targetP=0,smoothP=0,dragOffset=0,dragTarget=0,dragging=false,startX=0,startY=0,horizontal=false,car=null,carBaseY=.03,lastScrollY=0;
function sceneFor(p){for(let i=cuts.length-2;i>=0;i--)if(p>=cuts[i])return i;return 0}
function localFor(p,i){return THREE.MathUtils.clamp((p-cuts[i])/(cuts[i+1]-cuts[i]),0,1)}
const shots=[{pos:[4.7,1.25,-5.8],tar:[0,.62,-.15],fov:43,roll:-.025},{pos:[3.8,.92,-5.1],tar:[0,.55,-.65],fov:38,roll:-.018},{pos:[-1.55,.62,-2.15],tar:[-.82,.42,-1.45],fov:29,roll:.02},{pos:[-5.5,1.0,-.9],tar:[0,.62,-.2],fov:39,roll:0},{pos:[4.4,1.15,4.8],tar:[0,.65,.7],fov:39,roll:.016},{pos:[4.9,1.8,-6.2],tar:[0,.66,0],fov:42,roll:-.01},{pos:[3.25,1.05,-5.7],tar:[0,.58,-.4],fov:43,roll:-.03},{pos:[-4.8,1.5,5.8],tar:[0,.63,.4],fov:43,roll:.008}];
function cameraShot(i,l){let p=shots[i].pos,t=shots[i].tar,f=shots[i].fov,roll=shots[i].roll;if(i===0)p=[4.7-.45*l,1.25+.06*l,-5.8+.32*l];if(i===1)p=[3.8-.4*l,.92+.04*l,-5.1+.24*l];if(i===2)p=[-1.55+.10*l,.62,-2.15+.12*l];if(i===3){p=[-5.5,1,-1.25+2.5*l];t=[0,.62,-.9+1.8*l]}if(i===4)p=[4.4-.25*l,1.15+.08*l,4.8-.35*l];if(i===5)p=[4.9-.75*l,1.8-.15*l,-6.2+.55*l];if(i===6){p=[3.25-.45*l,1.05+.06*Math.sin(l*Math.PI),-5.7+.2*l];roll=-.03+.015*Math.sin(l*Math.PI*2)}if(i===7)p=[-4.8+.25*l,1.5,5.8-.2*l];const pos=new THREE.Vector3().fromArray(p),tar=new THREE.Vector3().fromArray(t);const dir=new THREE.Vector3().subVectors(tar,pos).normalize(),right=new THREE.Vector3().crossVectors(dir,camera.up).normalize();tar.addScaledVector(right,dragOffset*.9);camera.position.lerp(pos,.095);const look=new THREE.Matrix4().lookAt(camera.position,tar,new THREE.Vector3(0,1,0));const q=new THREE.Quaternion().setFromRotationMatrix(look);camera.quaternion.slerp(q,.11);camera.rotateZ(roll);camera.fov+=(f-camera.fov)*.08;camera.updateProjectionMatrix()}
function setEnv(i,l){env.studio.visible=i<6||i===7;env.grid.visible=i===1||i===5;env.platform.visible=i===5||i===7;env.track.visible=i===6;env.brakes.visible=i===2;redKick.intensity=i===2?18*(.4+Math.sin(l*Math.PI)*.6):i===7?3:0;amberKick.intensity=i===4?8:i===6?5:0;const head=i===1||i===6;env.headSpots.forEach(s=>s.intensity=head?22:0);env.headGlow.forEach(s=>s.material.opacity=head?.8:0);env.tailGlow.forEach(s=>s.material.opacity=(i===4||i===7)?.65:0);key.intensity=[1.1,5.2,3.4,4.4,3.2,5.8,3.8,2.1][i];rim.intensity=[1.8,4.4,2.2,5.4,4.8,5.2,2.8,3.4][i];key.color.set(i===4?0xffd5b0:0xffffff);rim.color.set(i===2?0xff6040:0x8bc7ff);renderer.toneMappingExposure=[.54,.93,.83,.85,.8,1.0,.82,.68][i];scene.fog.density=i===6?.032:i===7?.024:.016;floorMat.color.set(i===6?0x050505:0x080808);floorMat.roughness=i===5?.28:.48;if(env.brakes.visible)env.brakes.children.forEach(d=>d.material.opacity=.2+.65*Math.sin(Math.min(1,l*1.3)*Math.PI))}
function onScene(i){if(i===currentScene)return;currentScene=i;chapters.forEach((c,n)=>c.classList.toggle('active',n===i));sceneCode.textContent=String(i+1).padStart(2,'0');sceneName.textContent=sceneNames[i];giantNumber.textContent=String(i+1).padStart(2,'0');microCopy.textContent=micro[i];flash.classList.remove('hit');void flash.offsetWidth;flash.classList.add('hit')}
async function loadModel(){try{let b64='';for(let i=0;i<8;i++){const r=await fetch(`./model/part-${String(i).padStart(2,'0')}.txt?v=1`);if(!r.ok)throw new Error('asset '+i);b64+=await r.text();loaderPct.textContent=String(8+i*8).padStart(2,'0')}const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));let buf;if('DecompressionStream'in window){const ds=new DecompressionStream('gzip');buf=await new Response(new Blob([bin]).stream().pipeThrough(ds)).arrayBuffer()}else{const {ungzip}=await import('https://cdn.jsdelivr.net/npm/pako@2.1.0/+esm');buf=ungzip(bin).buffer}loaderPct.textContent='82';const gltf=await new Promise((res,rej)=>new GLTFLoader().parse(buf,'',res,rej));car=gltf.scene;car.rotation.x=Math.PI/2;const box=new THREE.Box3().setFromObject(car),center=box.getCenter(new THREE.Vector3());car.position.sub(center);const box2=new THREE.Box3().setFromObject(car);car.position.y-=box2.min.y;car.position.y+=carBaseY;car.traverse(o=>{if(o.isMesh){o.castShadow=!MOBILE;o.receiveShadow=!MOBILE;if(o.material){o.material.envMapIntensity=1.25;o.material.needsUpdate=true}}});carRoot.add(car);loaderPct.textContent='100';setTimeout(()=>loaderEl.classList.add('done'),220)}catch(e){console.error(e);loaderEl.querySelector('b').textContent='MODEL LOAD FAILED';loaderPct.textContent='ERR'}}
loadModel();
function readScroll(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);targetP=THREE.MathUtils.clamp(scrollY/max,0,1);dragTarget=0;if(scrollY!==lastScrollY){gesture.classList.add('hide');lastScrollY=scrollY}}
addEventListener('scroll',readScroll,{passive:true});readScroll();
canvas.addEventListener('touchstart',e=>{gesture.classList.add('hide');if(!e.touches[0])return;startX=e.touches[0].clientX;startY=e.touches[0].clientY;dragging=true;horizontal=false},{passive:true});
canvas.addEventListener('touchmove',e=>{if(!dragging||!e.touches[0])return;const dx=e.touches[0].clientX-startX,dy=e.touches[0].clientY-startY;if(!horizontal&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.18)horizontal=true;if(horizontal){e.preventDefault();dragTarget=THREE.MathUtils.clamp(dx/innerWidth,-.85,.85)}},{passive:false});
canvas.addEventListener('touchend',()=>{dragging=false;horizontal=false;dragTarget*=.55},{passive:true});
canvas.addEventListener('pointerdown',e=>{gesture.classList.add('hide');if(e.pointerType==='touch')return;dragging=true;startX=e.clientX});canvas.addEventListener('pointermove',e=>{if(dragging&&e.pointerType!=='touch')dragTarget=THREE.MathUtils.clamp((e.clientX-startX)/innerWidth,-.85,.85)});addEventListener('pointerup',()=>{dragging=false;dragTarget*=.55});
const clock=new THREE.Clock();let last=0;
function animate(t){requestAnimationFrame(animate);if(MOBILE&&t-last<31)return;last=t;const dt=Math.min(.05,clock.getDelta());smoothP+=(targetP-smoothP)*.065;dragOffset+=(dragTarget-dragOffset)*.12;if(!dragging)dragTarget*=.91;document.documentElement.style.setProperty('--p',smoothP.toFixed(4));progressBar.style.width=(smoothP*100)+'%';const i=sceneFor(smoothP),l=localFor(smoothP,i);onScene(i);setEnv(i,l);cameraShot(i,l);let rpm=[800,3400,6100,5200,7000,7600,8400,1200][i];if(i===6)rpm=6900+1500*l;if(i===2)rpm=6200-2500*l;rpmValue.textContent=String(Math.round(rpm/50)*50).padStart(4,'0');if(car){carRoot.rotation.y+=(0-carRoot.rotation.y)*.06;carRoot.position.set(0,0,0);carRoot.rotation.z=0;if(i===0)carRoot.rotation.y=-.06+.05*l;if(i===3)carRoot.position.z=.12*Math.sin(l*Math.PI);if(i===5)carRoot.rotation.y=.09*Math.sin(l*Math.PI*.8);if(i===6){carRoot.position.y=Math.sin(t*.025)*.006;carRoot.rotation.z=Math.sin(t*.018)*.0015}}if(i===6){const speed=dt*(20+36*l);env.dashes.forEach(d=>{d.position.z+=speed;if(d.position.z>22)d.position.z-=90});env.gantries.forEach(g=>{g.position.z+=speed*.7;if(g.position.z>28)g.position.z-=80})}renderer.render(scene,camera)}
requestAnimationFrame(animate);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width:780px)').matches?1.25:1.7));renderer.setSize(innerWidth,innerHeight,false)},{passive:true});
